#!/bin/sh

# Fail on error
set -e

echo "🚀 Starting Lume Server (Render Mode)..."

# 1. Generate config/passwords.yaml
# We use standard Serverpod password keys but populate them from ENV.
echo "🔑 Generating passwords.yaml..."
cat > config/passwords.yaml <<EOF
# Generated by run-render.sh
development:
  database: '${DB_PASS}'
  redis: '${REDIS_PASS}'
staging:
  database: '${DB_PASS}'
  redis: '${REDIS_PASS}'
production:
  database: '${DB_PASS}'
  redis: '${REDIS_PASS}'
  serviceSecret: '${LUME_SERVICE_SECRET}'
  emailSecretHashPepper: '${LUME_EMAIL_PEPPER}'
  jwtHmacSha512PrivateKey: '${LUME_JWT_PRIVATE_KEY}'
  jwtRefreshTokenHashPepper: '${LUME_JWT_PEPPER}'
EOF

# 2. Generate config/production.yaml
# We overwrite the default production.yaml to ensure it uses our ENV vars.
# We map Render's RENDER_EXTERNAL_URL to publicHost if available.
PUBLIC_HOST=${RENDER_EXTERNAL_URL#https://} 
PUBLIC_HOST=${PUBLIC_HOST#http://}
PUBLIC_HOST=${PUBLIC_HOST%%/*} # Strip path if any

# Default to localhost if not set (though Render should set it)
: ${PUBLIC_HOST:="localhost"}

echo "🌍 Configuring production.yaml for host: $PUBLIC_HOST"
cat > config/production.yaml <<EOF
# Generated by run-render.sh
apiServer:
  port: 8080
  publicHost: '${PUBLIC_HOST}'
  publicPort: 8080
  publicScheme: https

insightsServer:
  port: 8081
  publicHost: '${PUBLIC_HOST}'
  publicPort: 8081
  publicScheme: https

webServer:
  port: 8082
  publicHost: '${PUBLIC_HOST}'
  publicPort: 8082
  publicScheme: https

database:
  host: '${DB_HOST}'
  port: ${DB_PORT:-5432}
  name: '${DB_NAME}'
  user: '${DB_USER}'
  requireSsl: true

redis:
  enabled: false # Set to true if you have Redis
  host: '${REDIS_HOST}'
  port: ${REDIS_PORT:-6379}
  requireSsl: true

maxRequestSize: 524288
sessionLogs:
  consoleEnabled: false
EOF

# 3. Apply Migrations (Optional but recommended)
# echo "🛠️ Applying migrations..."
# ./server --mode=production --role=maintenance --apply-migrations

# 4. Start Server
echo "✅ Configuration complete. Starting Serverpod..."
exec ./server --mode=production --server-id=default --logging=normal --role=monolith
